//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoshiMiyamoto.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\TFDatabase.md" +
            "f;Integrated Security=True")]
        public string TFDatabaseConnectionString {
            get {
                return ((string)(this["TFDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\ThermoFisherD" +
            "B.mdf;Integrated Security=True;Connect Timeout=30")]
        public string ThermoFisherDBConnectionString {
            get {
                return ((string)(this["ThermoFisherDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\ThermoDB.mdf;" +
            "Integrated Security=True;Connect Timeout=30")]
        public string ThermoDBConnectionString {
            get {
                return ((string)(this["ThermoDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\YOSHI_000\\DESKTOP\\THE" +
            "RMOFISHER\\YOSHIMIYAMOTO\\YOSHIMIYAMOTO\\THERMODB.MDF;Integrated Security=True;Conn" +
            "ect Timeout=30;Encrypt=False;TrustServerCertificate=True")]
        public string C__USERS_YOSHI_000_DESKTOP_THERMOFISHER_YOSHIMIYAMOTO_YOSHIMIYAMOTO_THERMODB_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_YOSHI_000_DESKTOP_THERMOFISHER_YOSHIMIYAMOTO_YOSHIMIYAMOTO_THERMODB_MDFC" +
                    "onnectionString"]));
            }
        }
    }
}
